# Generated by Django 6.0.3 on 2026-05-17 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_created'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='projet',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projet',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed description for the project page'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(help_text='Main image for the project', upload_to='projets/'),
        ),
        migrations.CreateModel(
            name='ProjetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/illustrations/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.projet')),
            ],
        ),
    ]
